name: Terraform Scheduled Apply

on:
#   schedule:
#     - cron: '0 2 * * *'  # Every day at 2:00 AM UTC
  workflow_dispatch:

jobs:
  fetch-paths:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate matrix
        id: set-matrix
        run: |
            paths=$(find terraform/app1 -type f -name 'ec2.tf')

            matrix=$(echo "$paths" | while read -r path; do
            echo "{\"path\":\"$path\"}"
            done | jq -s '.')

            echo "matrix=$(echo "$matrix" | jq -c '.')" >> $GITHUB_OUTPUT

  apply-ami-patch:
    needs: fetch-paths
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(needs.fetch-paths.outputs.matrix) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Terraform Apply
        uses: paulpallab005/terraform-aws-actions/.github/workflows/terraform-apply.yml@main
        with:
            path: ${{ matrix.path }}

