name: Maven Build Test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        type: choice
        options:
          - main
          - develop

  push:
    branches:
      - feature/demo-2
    paths:
      - 'terraform/**'
      - '.github/workflows/set-maven.yml'

jobs:
  idm_build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git Branch
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "GITHUB_BRANCH_NAME=${{ github.event.inputs.branch }}" >> $GITHUB_ENV
          else
            echo "GITHUB_BRANCH_NAME=$(echo '${{ github.ref }}" >> $GITHUB_ENV
          fi
          echo "Git Branch to be used: ${GITHUB_BRANCH_NAME}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${GITHUB_BRANCH_NAME}

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      # - name: Cache Maven dependencies
      #   uses: actions/cache@v4
      #   with:
      #     path: ~/.m2/repository
      #     key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: |
      #       m2-${{ runner.os }}-

      - name: Show environment info
        run: |
          export M2_HOME=$(dirname $(dirname $(readlink -f $(which mvn))))
          echo "PATH = $PATH"
          echo "M2_HOME = $M2_HOME"

      # - name: Write Maven settings.xml
      #   run: |
      #     cat <<EOF > settings.xml
      #     ${{ secrets.MAVEN_SETTINGS_XML }}
      #     EOF

      - name: Build or Deploy OpenIDM
        run: |
          cd java
          # BRANCH_NAME="${GITHUB_BRANCH_NAME}"
          case "${GITHUB_BRANCH_NAME}" in
            develop|hotfix*|*release*)
              MVN_CMD="deploy"
              ;;
            *)
              MVN_CMD="install"
              ;;
          esac

          # Maven Build
          echo "Performing Maven $MVN_CMD for branch: $BRANCH_NAME"