name: Set Maven

on:
  workflow_dispatch:
  push:
    paths:
      - 'terraform/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IAM_TASK_SERVICE: iam-task-service
      POM: pom.xml
      GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      GITHUB_SHA: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      - name: Check previous workflow run status
        id: prev_status
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          WORKFLOW_NAME="${{ github.workflow }}"
          PREV_STATUS=$(gh run list --workflow="$WORKFLOW_NAME" --branch="$BRANCH_NAME" --limit 2 --json conclusion --jq '.[1].conclusion')
          echo "Previous run status: $PREV_STATUS"
          echo "prev_status=$PREV_STATUS" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Stop if last build was successful
        if: steps.prev_status.outputs.prev_status == 'success' && github.event_name == 'workflow_dispatch'
        run: |
          echo "Last build on this ${GITHUB_REF##*/} branch on ${{ github.event_name }} was successful. Skipping further steps."
          exit 1

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Maven 3.6.2
        run: | 
          wget https://archive.apache.org/dist/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
          tar -xzf apache-maven-3.6.2-bin.tar.gz
          echo "$PWD/apache-maven-3.6.2/bin" >> $GITHUB_PATH
          echo "M2_HOME=$PWD/apache-maven-3.6.2" >> $GITHUB_ENV

      - name: Show environment info
        run: |
          echo "PATH = $PATH"
          echo "M2_HOME = $M2_HOME"

      - name: Write Maven settings.xml
        run: echo "${{ secrets.MAVEN_SETTINGS_XML }}" > settings.xml
