name: Terragrunt Test

on:
  workflow_dispatch:

jobs:
  maven_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
            
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.4"

      - name: Get Terraform Path
        shell: bash
        id: get_tf_path
        run: |
          tf_path=$(which terraform)
          echo "tf_path=$tf_path" >> $GITHUB_OUTPUT
          echo "Terraform path: $tf_path"

      - name: Install Terragrunt
        uses: gruntwork-io/terragrunt-action@v3
        with:
          tg_version: "0.83.2"
          tf_path: ${{ steps.get_tf_path.outputs.tf_path }}

      - name: Display version
        run: |
          terraform --version
          terragrunt --version