name: Set Maven

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  filter:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      proceed_build: ${{ steps.check_changes.outputs.proceed_build }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get previous commit SHA
        id: prev_commit
        run: |
          PREV_SHA=$(git rev-parse HEAD~1)
          echo "prev_sha=$PREV_SHA" >> $GITHUB_OUTPUT

      - name: Check for changes in relevant files
        id: check_changes
        run: |
          git fetch --depth=2
          CHANGED=$(git diff --name-only ${{ steps.prev_commit.outputs.prev_sha }} HEAD)
          echo "$CHANGED"
          if echo "$CHANGED" | grep -qE '^terraform/'; then
            echo "proceed_build=true" >> $GITHUB_OUTPUT
          else
            echo "proceed_build=false" >> $GITHUB_OUTPUT
          fi

  set_value_push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      proceed_build: ${{ steps.set_value_push.outputs.proceed_build }}
    steps:
      - name: Set Value
        id: set_value_push
        run: echo "proceed_build=true" >> $GITHUB_OUTPUT

  set_value_dispatch:
    if: github.event_name == 'workflow_dispatch'
    needs: filter
    runs-on: ubuntu-latest
    outputs:
      proceed_build: ${{ steps.set_value_dispatch.outputs.proceed_build }}
    steps:
      - name: Set Value
        id: set_value_dispatch
        run: |
          if [[ "${{ needs.filter.outputs.proceed_build }}" == 'true' ]]; then
            echo "Terraform files have changed, proceeding with build."
            echo "proceed_build=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in Terraform files, skipping build."
            echo "proceed_build=false" >> $GITHUB_OUTPUT
            exit 0
          fi

  build:
    runs-on: ubuntu-latest
    needs: [set_value_push, set_value_dispatch]
    if: always() && (needs.set_value_push.outputs.proceed_build == 'true' || needs.set_value_dispatch.outputs.proceed_build == 'true')
    env:
      IAM_TASK_SERVICE: iam-task-service
      POM: pom.xml
      GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      GITHUB_SHA: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Maven 3.6.2
        run: | 
          wget https://archive.apache.org/dist/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
          tar -xzf apache-maven-3.6.2-bin.tar.gz
          echo "$PWD/apache-maven-3.6.2/bin" >> $GITHUB_PATH
          echo "M2_HOME=$PWD/apache-maven-3.6.2" >> $GITHUB_ENV

      - name: Show environment info
        run: |
          echo "PATH = $PATH"
          echo "M2_HOME = $M2_HOME"

      - name: Write Maven settings.xml
        run: echo "${{ secrets.MAVEN_SETTINGS_XML }}" > settings.xml

      # - name: Build or Deploy iam-task-service
      #   run: |
      #     cd java
      #     BRANCH_NAME="${GITHUB_REF##*/}"
      #     if [[ "$BRANCH_NAME" == "develop" ]] || [[ "$BRANCH_NAME" == hotfix* ]] || [[ "$BRANCH_NAME" == *release* ]]; then
      #       MVN_CMD="deploy"
      #     else
      #       MVN_CMD="install"
      #     fi
      #     mvn -s ../settings.xml clean $MVN_CMD -P $IAM_TASK_SERVICE \
      #       -Dgithub.build_number=${GITHUB_BUILD_NUMBER} \
      #       -Dgithub.build_url=${GITHUB_RUN_URL} \
      #       -Dgithub.git_commit=${GITHUB_SHA}
      #dummy commit