name: routing_multibranch

on:
  workflow_dispatch:
  push:
    branches:
      - feature/IDAMDO-1438
      - develop
      - 'hotfix*'
      - '*release*'
    paths:
      - 'java/iam-task-service/**'
      - 'java/pom.xml'
      - '.github/workflows/routing-build.yml'

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      terraform_changed: ${{ steps.filter.outputs.terraform_changed }}
      # iam_changed: ${{ steps.filter.outputs.iam_task_service }}
      # pom_changed: ${{ steps.filter.outputs.pom }}
      # gh_workflow_file_changed: ${{ steps.filter.outputs.gh_workflow_file }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            # iam_task_service:
            #   - 'java/iam-task-service/**'
            # pom:
            #   - 'java/pom.xml'
            # gh_workflow_file:
            #   - '.github/workflows/routing-build.yml'
            terraform:
              - 'terraform/**'

  build:
    needs: filter
    runs-on: ubuntu-latest
    if: needs.filter.outputs.terraform_changed == 'true'
    # if: needs.filter.outputs.iam_changed == 'true' || needs.filter.outputs.pom_changed == 'true' || needs.filter.outputs.gh_workflow_file_changed == 'true'
    env:
      IAM_TASK_SERVICE: iam-task-service
      POM: pom.xml
      GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      GITHUB_SHA: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Maven 3.6.2
        run: | 
          wget https://archive.apache.org/dist/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
          tar -xzf apache-maven-3.6.2-bin.tar.gz
          echo "$PWD/apache-maven-3.6.2/bin" >> $GITHUB_PATH
          echo "M2_HOME=$PWD/apache-maven-3.6.2" >> $GITHUB_ENV

      - name: Show environment info
        run: |
          echo "PATH = $PATH"
          echo "M2_HOME = $M2_HOME"

      - name: Write Maven settings.xml
        run: echo "${{ secrets.MAVEN_SETTINGS_XML }}" > settings.xml

      - name: Build or Deploy iam-task-service
        run: |
          cd java
          BRANCH_NAME="${GITHUB_REF##*/}"
          if [[ "$BRANCH_NAME" == "develop" ]] || [[ "$BRANCH_NAME" == hotfix* ]] || [[ "$BRANCH_NAME" == *release* ]]; then
            MVN_CMD="deploy"
          else
            MVN_CMD="install"
          fi
          mvn -s ../settings.xml clean $MVN_CMD -P $IAM_TASK_SERVICE \
            -Dgithub.build_number=${GITHUB_BUILD_NUMBER} \
            -Dgithub.build_url=${GITHUB_RUN_URL} \
            -Dgithub.git_commit=${GITHUB_SHA}