name: Set Maven

on:
  workflow_dispatch:
    inputs:
      criteria_create:
        description: 'Criteria: create'
        type: boolean
        required: false
        default: false
      criteria_modify:
        description: 'Criteria: modify'
        type: boolean
        required: false
        default: false
      criteria_lastlogin:
        description: 'Criteria: lastlogin'
        type: boolean
        required: false
        default: false
      criteria_pearsonlastlogin:
        description: 'Criteria: pearsonlastlogin'
        type: boolean
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IAM_TASK_SERVICE: iam-task-service
      POM: pom.xml
      GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      GITHUB_SHA: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Maven 3.6.2
        run: |
          # Build criteria string based on user input
          criteria=""
          if [ "${{ inputs.criteria_create }}" = "true" ]; then
            criteria="create"
          fi
          if [ "${{ inputs.criteria_modify }}" = "true" ]; then
            if [ -n "$criteria" ]; then criteria="$criteria,modify"; else criteria="modify"; fi
          fi
          if [ "${{ inputs.criteria_lastlogin }}" = "true" ]; then
            if [ -n "$criteria" ]; then criteria="$criteria,lastlogin"; else criteria="lastlogin"; fi
          fi
          if [ "${{ inputs.criteria_pearsonlastlogin }}" = "true" ]; then
            if [ -n "$criteria" ]; then criteria="$criteria,pearsonlastlogin"; else criteria="pearsonlastlogin"; fi
          fi

          echo "Selected criteria: $criteria"

          if [ -z "$criteria" ]; then
            echo "No criteria selected. Please select at least one criteria."
            exit 1
          fi
          wget https://archive.apache.org/dist/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
          tar -xzf apache-maven-3.6.2-bin.tar.gz
          echo "$PWD/apache-maven-3.6.2/bin" >> $GITHUB_PATH
          echo "M2_HOME=$PWD/apache-maven-3.6.2" >> $GITHUB_ENV

      - name: Show environment info
        run: |
          echo "PATH = $PATH"
          echo "M2_HOME = $M2_HOME"