name: Set Maven

on:
  workflow_dispatch:
    inputs:
      criteria:
        description: 'User criteria (select one or more)'
        required: true
        type: choice
        options:
        - create
        - modify
        - lastlogin
        - pearsonlastlogin

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IAM_TASK_SERVICE: iam-task-service
      POM: pom.xml
      GITHUB_BUILD_NUMBER: ${{ github.run_number }}
      GITHUB_RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      GITHUB_SHA: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Maven 3.6.2
        run: |
          echo "Selected criteria: ${{ inputs.criteria }}"
          wget https://archive.apache.org/dist/maven/maven-3/3.6.2/binaries/apache-maven-3.6.2-bin.tar.gz
          tar -xzf apache-maven-3.6.2-bin.tar.gz
          echo "$PWD/apache-maven-3.6.2/bin" >> $GITHUB_PATH
          echo "M2_HOME=$PWD/apache-maven-3.6.2" >> $GITHUB_ENV

      - name: Show environment info
        run: |
          echo "PATH = $PATH"
          echo "M2_HOME = $M2_HOME"